### ISSUE TITLE
Heroku crashes on Mongo access

### ISSUE THREAD

**Issue by 42mileslong** [CS196Illinois/schedule-optimizer#65]
```
2017-12-11T01:01:04.106082+00:00 app[web.1]: events.js:183
2017-12-11T01:01:04.106084+00:00 app[web.1]:       throw er; // Unhandled 'error' event
2017-12-11T01:01:04.106085+00:00 app[web.1]:       ^
2017-12-11T01:01:04.106086+00:00 app[web.1]: 
2017-12-11T01:01:04.106087+00:00 app[web.1]: TypeError: Cannot read property 'iter_id' of null
2017-12-11T01:01:04.106088+00:00 app[web.1]:     at /app/src/server/api/index.js:50:40
2017-12-11T01:01:04.106089+00:00 app[web.1]:     at model.Query.<anonymous> (/app/node_modules/mongoose/lib/model.js:4046:16)
2017-12-11T01:01:04.106089+00:00 app[web.1]:     at /app/node_modules/kareem/index.js:273:21
2017-12-11T01:01:04.106090+00:00 app[web.1]:     at /app/node_modules/kareem/index.js:131:16
2017-12-11T01:01:04.106091+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:131:7)
2017-12-11T01:01:04.106092+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by 42mileslong** [comment]
Using the wrong db url
